apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: obc-watcher
rules:
  - verbs:
      - get
      - watch
      - list
      - patch
    apiGroups:
      - objectbucket.io
    resources:
      - objectbucketclaims
