kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: obc-watcher
subjects:
  - kind: ServiceAccount
    name: obc-watcher
    namespace: obc-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: obc-watcher
