apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/fallmo/obc-watcher.git
  labels:
    app: obc-watcher
    app.openshift.io/runtime: golang
  name: obc-watcher
  namespace: obc-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obc-watcher
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: obc-watcher
    spec:
      serviceAccountName: obc-watcher
      containers:
        - name: obc-watcher
          image: quay.io/mohamedf0/obc-watcher:v1
          env:
            - name: RABBITMQ_URI
              value: amqp://rabbitmq:5672
